# controller_manager:
#   ros__parameters:
#     update_rate: 50

# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50

# # effort_controllers:
#   joint1_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint1
#     pid: {p: 4.6, i: 0.3, d:  0.45,i_clamp_min: -2, i_clamp_max: 2, antiwindup: true}

#   joint2_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint2
#     pid: {p: 6.0, i: 0.5, d: 0.1, i_clamp_min: -2, i_clamp_max: 2, antiwindup: true}
    
#   joint3_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint3
#     pid: {p: 1.0, i: 0.1 , d: 0.1,i_clamp_min: -10, i_clamp_max: 10, antiwindup: true}

#   joint4_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint4
#     pid: {p: 1.0, i: 0.1, d: 0.1,i_clamp_min: -10, i_clamp_max: 10, antiwindup: true}

# effort_controllers:
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 3.2, i: 0.2, d:  0.6,i_clamp_min: -1.4, i_clamp_max: 1.4, antiwindup: true}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 6.0, i: 0.5, d: 0.4, i_clamp_min: -3.0, i_clamp_max: 3.0, antiwindup: true}
    
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 6.0, i: 1.5 , d: 0.4,i_clamp_min: -5, i_clamp_max: 5, antiwindup: true}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 6.0, i: 2.5, d: 0.3,i_clamp_min: -2, i_clamp_max: 2, antiwindup: true}

# # Effort Position Controllers ---------------------------------------
# joint1_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint1
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint2_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint2
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint3_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint3
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint4_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint4
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# Simple Position Controllers -----------------------------
# joint1_position_controller:
#     type: position_controllers/JointPositionController
#     joint: joint1
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint2_position_controller:
#     type: position_controllers/JointPositionController
#     joint: joint2
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint3_position_controller:
#     type: position_controllers/JointPositionController
#     joint: joint3
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint4_position_controller:
#     type: position_controllers/JointPositionController
#     joint: joint4
#     pid: {p: 1.0, i: 0.1, d: 0.01}