joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 1.0, i: 0.1, d: 0.01}

joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0.1, d: 0.01}

