joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 1.0
    motor:
        id: 11
        init: 0
        min: 0
        max: 4095
        
joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 1.0
    motor:
        id: 12
        init: 0
        min: 0
        max: 4095
        