// Generated by gencpp from file bioin_tacto/bias_srvRequest.msg
// DO NOT EDIT!


#ifndef BIOIN_TACTO_MESSAGE_BIAS_SRVREQUEST_H
#define BIOIN_TACTO_MESSAGE_BIAS_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bioin_tacto
{
template <class ContainerAllocator>
struct bias_srvRequest_
{
  typedef bias_srvRequest_<ContainerAllocator> Type;

  bias_srvRequest_()
    : num_secs(0)  {
    }
  bias_srvRequest_(const ContainerAllocator& _alloc)
    : num_secs(0)  {
  (void)_alloc;
    }



   typedef int16_t _num_secs_type;
  _num_secs_type num_secs;





  typedef boost::shared_ptr< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct bias_srvRequest_

typedef ::bioin_tacto::bias_srvRequest_<std::allocator<void> > bias_srvRequest;

typedef boost::shared_ptr< ::bioin_tacto::bias_srvRequest > bias_srvRequestPtr;
typedef boost::shared_ptr< ::bioin_tacto::bias_srvRequest const> bias_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bioin_tacto::bias_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bioin_tacto::bias_srvRequest_<ContainerAllocator1> & lhs, const ::bioin_tacto::bias_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num_secs == rhs.num_secs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bioin_tacto::bias_srvRequest_<ContainerAllocator1> & lhs, const ::bioin_tacto::bias_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bioin_tacto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ca836a613133c666e1004286aa0e937";
  }

  static const char* value(const ::bioin_tacto::bias_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ca836a613133c66ULL;
  static const uint64_t static_value2 = 0x6e1004286aa0e937ULL;
};

template<class ContainerAllocator>
struct DataType< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bioin_tacto/bias_srvRequest";
  }

  static const char* value(const ::bioin_tacto::bias_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 num_secs\n"
;
  }

  static const char* value(const ::bioin_tacto::bias_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_secs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bias_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bioin_tacto::bias_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bioin_tacto::bias_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "num_secs: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num_secs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOIN_TACTO_MESSAGE_BIAS_SRVREQUEST_H
