// Generated by gencpp from file bioin_tacto/raw_barometer.msg
// DO NOT EDIT!


#ifndef BIOIN_TACTO_MESSAGE_RAW_BAROMETER_H
#define BIOIN_TACTO_MESSAGE_RAW_BAROMETER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bioin_tacto
{
template <class ContainerAllocator>
struct raw_barometer_
{
  typedef raw_barometer_<ContainerAllocator> Type;

  raw_barometer_()
    : header()
    , sensor_id(0)
    , tempe(0.0)
    , baro_level(0.0)  {
    }
  raw_barometer_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_id(0)
    , tempe(0.0)
    , baro_level(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef float _tempe_type;
  _tempe_type tempe;

   typedef float _baro_level_type;
  _baro_level_type baro_level;





  typedef boost::shared_ptr< ::bioin_tacto::raw_barometer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bioin_tacto::raw_barometer_<ContainerAllocator> const> ConstPtr;

}; // struct raw_barometer_

typedef ::bioin_tacto::raw_barometer_<std::allocator<void> > raw_barometer;

typedef boost::shared_ptr< ::bioin_tacto::raw_barometer > raw_barometerPtr;
typedef boost::shared_ptr< ::bioin_tacto::raw_barometer const> raw_barometerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bioin_tacto::raw_barometer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bioin_tacto::raw_barometer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bioin_tacto::raw_barometer_<ContainerAllocator1> & lhs, const ::bioin_tacto::raw_barometer_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sensor_id == rhs.sensor_id &&
    lhs.tempe == rhs.tempe &&
    lhs.baro_level == rhs.baro_level;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bioin_tacto::raw_barometer_<ContainerAllocator1> & lhs, const ::bioin_tacto::raw_barometer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bioin_tacto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bioin_tacto::raw_barometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bioin_tacto::raw_barometer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioin_tacto::raw_barometer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bioin_tacto::raw_barometer_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioin_tacto::raw_barometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bioin_tacto::raw_barometer_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bioin_tacto::raw_barometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f8059946af2eac503e357862e785812";
  }

  static const char* value(const ::bioin_tacto::raw_barometer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f8059946af2eac5ULL;
  static const uint64_t static_value2 = 0x03e357862e785812ULL;
};

template<class ContainerAllocator>
struct DataType< ::bioin_tacto::raw_barometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bioin_tacto/raw_barometer";
  }

  static const char* value(const ::bioin_tacto::raw_barometer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bioin_tacto::raw_barometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16 sensor_id\n"
"float32 tempe\n"
"float32 baro_level\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bioin_tacto::raw_barometer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bioin_tacto::raw_barometer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_id);
      stream.next(m.tempe);
      stream.next(m.baro_level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct raw_barometer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bioin_tacto::raw_barometer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bioin_tacto::raw_barometer_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.sensor_id);
    s << indent << "tempe: ";
    Printer<float>::stream(s, indent + "  ", v.tempe);
    s << indent << "baro_level: ";
    Printer<float>::stream(s, indent + "  ", v.baro_level);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIOIN_TACTO_MESSAGE_RAW_BAROMETER_H
