(cl:defpackage OMX_teleop-srv
  (:use )
  (:export
   "ROBOTINSTRUCTION"
   "<ROBOTINSTRUCTION-REQUEST>"
   "ROBOTINSTRUCTION-REQUEST"
   "<ROBOTINSTRUCTION-RESPONSE>"
   "ROBOTINSTRUCTION-RESPONSE"
  ))

