gripper_position:
  type: effort_controllers/JointPositionController
  joint: gripper
  pid: {p: 0.1, i: 0.01, d: 0.01}
gripper_sub_position:
  type: effort_controllers/JointPositionController
  joint: gripper_sub
  pid: {p: 0.1, i: 0.01, d: 0.01}
