# Effort Position Controllers ---------------------------------------
# joint1_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint1
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint2_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint2
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint3_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint3
#     pid: {p: 1.0, i: 0.1, d: 0.01}

# joint4_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint4
#     pid: {p: 1.0, i: 0.1, d: 0.01}
    

joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 1.0, i: 0.1, d: 0.01}

joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0.1, d: 0.01}

joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 1.0, i: 0.1, d: 0.01}

joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint4
    pid: {p: 1.0, i: 0.1, d: 0.01}
