// Generated by gencpp from file OMX_teleop/RobotInstructionRequest.msg
// DO NOT EDIT!


#ifndef OMX_TELEOP_MESSAGE_ROBOTINSTRUCTIONREQUEST_H
#define OMX_TELEOP_MESSAGE_ROBOTINSTRUCTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace OMX_teleop
{
template <class ContainerAllocator>
struct RobotInstructionRequest_
{
  typedef RobotInstructionRequest_<ContainerAllocator> Type;

  RobotInstructionRequest_()
    : input_char()  {
    }
  RobotInstructionRequest_(const ContainerAllocator& _alloc)
    : input_char(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _input_char_type;
  _input_char_type input_char;





  typedef boost::shared_ptr< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotInstructionRequest_

typedef ::OMX_teleop::RobotInstructionRequest_<std::allocator<void> > RobotInstructionRequest;

typedef boost::shared_ptr< ::OMX_teleop::RobotInstructionRequest > RobotInstructionRequestPtr;
typedef boost::shared_ptr< ::OMX_teleop::RobotInstructionRequest const> RobotInstructionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator1> & lhs, const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input_char == rhs.input_char;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator1> & lhs, const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace OMX_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1638d55a7107e0f1b809aa10f6c3fb";
  }

  static const char* value(const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1638d55a7107e0ULL;
  static const uint64_t static_value2 = 0xf1b809aa10f6c3fbULL;
};

template<class ContainerAllocator>
struct DataType< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "OMX_teleop/RobotInstructionRequest";
  }

  static const char* value(const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input_char\n"
;
  }

  static const char* value(const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_char);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotInstructionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::OMX_teleop::RobotInstructionRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_char: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.input_char);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMX_TELEOP_MESSAGE_ROBOTINSTRUCTIONREQUEST_H
